### PR TITLE
Remove `cml publish` pipe from examples

### LINKED ISSUE #1000: fix `cml publish` stdin pipe
- either find a solution to #983, https://github.com/iterative/cml/pull/732#issue-1004203281, https://github.com/iterative/cml/pull/67#discussion_r415530205, https://github.com/yargs/yargs/issues/1312, https://github.com/nodejs/node/issues/42826
  + e.g. use [get-stdin](https://www.npmjs.com/package/get-stdin)
- or update our docs everywhere
  + replace `some_cmd | cml publish` with `some_cmd > /tmp/file; cml publish /tmp/file` and/or `cml publish <(some_cmd)`

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Closes https://github.com/iterative/cml/issues/1000 along with all the pull requests listed in https://github.com/iterative/cml/issues/1000#issuecomment-1124628318

### CODE REVIEW

**Comment by shcheklein** [comment]
@iesahin @tapadipti @jorgeorpinel do we use this project anywhere?

**Comment by tapadipti** [comment]
yes, there's a view in the Iterative team dashboard in Studio. I've use it in the Studio product update emails. But I recreate this repo sometimes, so I'll have to take the proposed changes and make them in my repo generator script.

**Comment by casperdcl** [comment]
Where's the source generator repo?

**Comment by shcheklein** [comment]
@tapadipti also, what are the requirements for this repo from the Studio perspective, @iesahin is working on the deep learning dvcline `dvc-experiments` one - can we cover it there? 

how many commits do we need, branches, what kind of plots?

**Comment by tapadipti** [comment]
> Where's the source generator repo?

The source generator isn't pushed. It was added in this PR: https://github.com/iterative/example-repos-dev/pull/91, but we decided not to merge it, in order to not have too many example repos.

> requirements for this repo from the Studio perspective

So far,
- multiple image plots
- multiple merged plots
- plots sub-directories

But I use this repo to add features as I need them when writing the Studio product emails. Since those emails are not planned/designed too much in advance, I make the required changes and regenerate the repo quickly (usually in 1-2 days before sending the email). Not sure it'll be that easy/quick to make changes in the shared deep learning repo.

**Comment by shcheklein** [comment]
@iesahin let's make sure that the new update covers this please and Tapa has enough info out of it please?

so that we can archive this, use same projects and keep improving them

**Comment by shcheklein** [comment]
Closing this for a lot of reasons ^^.

**Pull request closed without merging**
